# Generated by Django 3.0.6 on 2020-08-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_searcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fieldName',
        ),
        migrations.AddField(
            model_name='post',
            name='PDF',
            field=models.FileField(default=7, upload_to='media/'),
            preserve_default=False,
        ),
    ]
